title: Ashley Santiago
description: Ecologist · Golden Eagle Research · Quantitative Ecology
url: "https://AshSantiago.github.io"

theme: minima

minima:
  skin: classic

header_pages:
  - about.md
  - research.md
  - publications.md
  - cv.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
